### ISSUE TITLE
Doesn't check each single strategy.

### ISSUE THREAD

**Issue by venikman** [futurestudio/hapi-auth-multiple-strategies#5] opened 2019-02-06 15:53 UTC
We have 2 strategies that we combine with `multiple-strategies` but when the first strategy is passing but second doesn't route validate scopes too late. 
Looks like there is no code written that will check every single strategy before handler.

**Comment by marcuspoehls** [comment] 2019-02-06 16:04
@venikman Hey! What hapi version do you use?

**Comment by marcuspoehls** [comment] 2019-02-06 16:06
@venikman Another question, are you defining scopes as an array?

**Comment by venikman** [comment] 2019-02-06 16:07
we using `hapi@17` with your `1.0.2`.
```
    server.auth.strategy('login-and-connect', 'multiple-strategies', {
        strategies : ['session', 'stripe']
    });
```

**Comment by marcuspoehls** [comment] 2019-02-06 16:27
@venikman At this point, testing all strategies runs concurrently. If one of the strategies fail, the catch block returns `h.unauthenticated`.

Can you confirm that?

I think your issue description indicates that scope validation still happens on the route, but that shouldn't happen

**Comment by marcuspoehls** [comment] 2019-02-06 20:48
@venikman I’ve published new versions `1.0.3` for hapi 17 and `2.0.2` for hapi. Both versions test each authentication strategy in sequence.

Please let me know if this fixes your problem. Thanks :)

**Comment by venikman** [comment] 2019-02-07 00:15
Unfortunately, it didn't help =( 
Looks like hapi anyway run all strategies and only after done with it, checking scopes...
I will try to fix somehow on my side and will update you with results. 
But anyway thank you for syper fast response and update @marcuspoehls

**Comment by marcuspoehls** [comment] 2019-02-07 05:49
I don't think the issue is in hapi itself. Can you please share more about your setup? (Route, auth strategies, how do the credentials look like with and without scope)

**Comment by venikman** [comment] 2019-02-07 14:25
Sure. 
```js
module.exports = {
    method : 'GET',
    path   : '/multiple-strategies',
    config : {
        auth        : {
            strategy : 'login-and-connect',
            mode     : 'required',
            scope    : ['scope-added-by-session-startegy']
        },
    async handler(request, h) {
         return {}
    }
```
We use [hapi-doorkeeper](https://github.com/sholladay/hapi-doorkeeper) for `hapi-auth-cookie` where we have `validateFunc` which set scope in the end:
```js
 validateFunc     : async (request, session) => {
                    return {
                        valid       : true,
                        credentials : {
                            ...session,
                            scope : user.type
                        }
                    };
                }
```
And second startegy use `bell` where it depends on user type, if scope set by `session` - `firstType` it doesn't do redirect but if `seconsType` it should redirect.

**Comment by marcuspoehls** [comment] 2019-02-07 14:50
@venikman It's hard more me to debug your code, but it seems like the `bell` strategy depends on the first strategy. The `bell` strategy has different behavior depending on the outcome of the first strategy. And I guess you'll always see the behavior where the scope is not set. Is that correct?

What I would do to find more details:
- debug the `bell` strategy and check the scope-value that should have been set by the `session` strategy
- if you need to pass values from one strategy to another, use request decorations. The latest version of `hapi-auth-multiple-strategies` runs the auth checks in sequence and you could decorate the request object in your first strategy and use this value in your second strategy (well, I didn't test this but I guess it should work :) )

Hope that helps!

**Comment by marcuspoehls** [comment] 2019-02-14 16:19
@venikman Hey Stan, how's it going with this issue? Did you find the problem?

**Comment by marcuspoehls** [comment] 2019-02-18 10:02
@venikman Closing this issue here. Please reopen or reach out if you want more help :)

**Closed by marcuspoehls** 2019-02-18 10:02 UTC
